[[prefix]]
modes = ["x"]
prefix = "aa"
include = true
list = ["mc", "mb", "ml", "rxc", "rxcb", "rxs", "sl", "sle", "slb", "sfw", "sc", "d", "i", "a", "gse", "gsb"]

[[keybind]]
modes = []
invalid_modes = ["x"]
keys = ["c"]
commands = ["pm x"]
desc = "Enter Multicursor Mode"

[[keybind]]
modes = []
invalid_modes = ["x"]
keys = ["shift-c"]
commands = ["cc", "ml 1"]
desc = "Create cursor"

[[keybind]]
modes = []
keys = ["shift-,"]
commands = ["dc"]
desc = "Delete Primary Cursor"

[[keybind]]
modes = []
keys = [","]
commands = ["dcs", "cm n"]
desc = "Delete Other Cursors, Go To Normal Mode"

[[keybind]]
modes = []
keys = ['[']
commands = ['cac -1']
desc = "Change Primary Cursor Up"

[[keybind]]
modes = []
keys = [']']
commands = ['cac 1']
desc = "Change Primary Cursor Down"
