[[keybind]]
modes = []
keys = ["o"]
commands = ["start_change", "sle false", "gse", "sc", "ts_nl", "gse", "sc", "pm i"]
desc = "Start insert at new line"

[[keybind]]
modes = []
keys = ["shift-o"]
commands = ["start_change", "slb false", "gsb", "sc", "ts_nl", "ml -1", "pm i"]
desc = "Start insert at new line before"
