[[keybind]]
modes = ["n"]
keys = ["space", "k"]
commands = ['hover']
desc = "Show Hover"

[[keybind]]
modes = ["i"]
keys = ["tab"]
commands = ['ala']
desc = "Accept LSP change"
required_templates = ['lsp_items']

# Make lsp start autocompletion on debounce of 100ms
[[plugin.debounce_event]]
modes = ["i"]

min_ms = 100
events = ['sla']
