[[keybind]]
modes = ["n"]
keys = ["space", "k"]
commands = ['hover']
desc = "Show Hover"

[[keybind]]
modes = ["i"]
keys = ["alt-space"]
commands = ['start_request']
desc = "Start LSP request"

[[keybind]]
modes = ["i"]
keys = ["tab"]
commands = ['accept']
desc = "Accept LSP change"
required_templates = ['lsp_items']
