[[keybind]]
modes = ["n"]
keys = ["space", "k"]
commands = ['hover']
desc = "Show Hover"

[[keybind]]
modes = ["i"]
keys = ["tab"]
commands = ['snlc']
desc = "Select next LSP change"
required_templates = ['lsp_items']

[[keybind]]
modes = ["i"]
keys = ["down"]
commands = ['snlc']
desc = "Select next LSP change"
required_templates = ['lsp_items']

[[keybind]]
modes = ["i"]
keys = ["up"]
commands = ['splc']
desc = "Select previous LSP change"
required_templates = ['lsp_items']

[[keybind]]
modes = ["i"]
keys = ["enter"]
commands = ['ala']
desc = "Select previous LSP change"
required_templates = ['lsp_items']

[[keybind]]
modes = ["i"]
keys = ["esc"]
commands = ['tla', "rm"]
desc = "Trash LSP change and drop move"
required_templates = ['lsp_items']

[[keybind]]
modes = []
keys = ["ctrl-(j|down)"]
commands = ["hs 1"]
desc = "Scroll Hover Down 1"

[[keybind]]
modes = []
keys = ["ctrl-(k|up)"]
commands = ["hs -1"]
desc = "Scroll Hover Up 1"

# Make lsp start autocompletion on debounce of 100ms
[[plugin.debounce_event]]
modes = ["i"]

min_ms = 100
events = ['sla']
