[[keybind]]
modes = []
keys = [";", "shift-q"]
commands = ["quit"]
desc = "Quit"

[[keybind]]
modes = []
keys = [";", "w"]
commands = ["write_file"]
desc = "Save file"

[[keybind]]
modes = []
keys = ["u"]
commands = ["undo"]
desc = "Undo"

[[keybind]]
modes = []
keys = ["shift-u"]
commands = ["redo"]
desc = "Undo"

[[keybind]]
modes = []
keys = ["g", "n"]
commands = ["bm 1"] 
desc = "Next Buffer"

[[keybind]]
modes = []
keys = ["g", "p"]
commands = ["bm -1"] 
desc = "Previous Buffer"

[[keybind]]
modes = []
keys = [";", "q"]
commands = ["bc"]
desc = "Close current buffer"
