[[import]]
# Just import theme here for organization
paths = ["./theme.toml"]

[[import]]
# Import all keybind modules. This is by default vim style bindings
paths = ["./vim/init.toml", "./utils/init.toml"]

[[import]]
# Import all plugin configs
paths = ["./plugins/init.toml"]

[core]
framerate = 60

[template]
cfg_folder = [ "/home/brightonlcox/programming/tools/Kerbin/config/" ]

shell = [ "nu" ]
