# This file defines special templates used by many core systems

[[keybind]]
modes = []
invalid_modes = []
keys = ["I"]
commands = ["pm I"]
desc = "Enter Special Insert Mode"

[[keybind]]
modes = ['I']
invalid_modes = []
keys = ["%alphabet"]
commands = ["a %0 false"]
desc = "Insert character"

[template]
alphabet = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
]
cap_alphabet = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
]
numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
symbols = [
  "{",
  "}",
  "[",
  "]",
  "(",
  ")",
  "\"",
  "'",
  "<",
  ">",
  ",",
  ".",
  "=",
  "-",
  "+",
  "-",
  "\\",
  "|",
  "/",
  "?",
  ";",
  ":",
  "!",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
  "`",
  "~",
]
