[[group]]
sequence = ["x"]
desc = "Group A"

[[keybind]]
sequence = ["X", "ctrl-shift-x"]
action = "hi"
desc = "hello, world :)"

[[keybind]]
sequence = ["*-x"]
action = "hello, world"
desc = "Yes"

[[keybind]]
sequence = ["x", "%digits"]
action = "quit"
desc = "Quit"

[[keybind]]
sequence = ["x", "9"]
action = "hello, world"
desc = "Cool keybind"

[[keybind]]
sequence = ["space", "$(echo \"h\")"]
action = "quit"
desc = "Shell Quit"

[[keybind]]
sequence = ["q"]
action = "quit"
desc = "Quit"
