[package]
name = "kerbin-input"
version.workspace = true
edition.workspace = true

[dependencies]
ascii-forge.workspace = true

thiserror.workspace = true

shellwords = "1.1.0"

serde = { version = "1.0.228", features = ["derive"], optional = true }
indexmap = "2.12.0"

[dev-dependencies]
serde_json = "1.0.145"
toml = "0.9.8"

[features]
serde = ["dep:serde"]

[[example]]
name = "toml"
required-features = ["serde"]
