[package]
name = "config"
version = "0.0.0"
edition = "2024"

[dependencies]
kerbin-core = { path = "../kerbin-core" }

# Plugins
kerbin-tree-sitter = { path = "../plugins/kerbin-tree-sitter" }
kerbin-lsp = { path = "../plugins/kerbin-lsp" }
tutor = { path = "../plugins/tutor" }
